
-- Step 1: Create a function to generate a unique 5-character alphanumeric ID.
CREATE OR REPLACE FUNCTION public.generate_unique_short_id()
RETURNS TEXT AS $$
DECLARE
  new_id TEXT;
  found_id TEXT;
  characters TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  char_length INT := length(characters);
BEGIN
  LOOP
    new_id := '';
    FOR i IN 1..5 LOOP
      new_id := new_id || substr(characters, (1 + floor(random() * char_length))::integer, 1);
    END LOOP;

    -- Check if the generated ID already exists in the profiles table.
    SELECT id INTO found_id FROM public.profiles WHERE id = new_id;
    
    IF found_id IS NULL THEN
      -- If it doesn't exist, exit the loop and return the new ID.
      EXIT;
    END IF;
    
    -- If it exists, the loop will continue and generate a new one.
  END LOOP;
  
  RETURN new_id;
END;
$$ LANGUAGE plpgsql VOLATILE;


-- Step 2: Ensure the profiles table exists with the necessary columns.
-- This block is idempotent and safe to run multiple times.
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'profiles') THEN
    CREATE TABLE public.profiles (
      id TEXT PRIMARY KEY,
      user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
      email TEXT UNIQUE,
      points INT DEFAULT 0,
      referral_code TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
  END IF;

  -- Add columns if they don't exist, for backwards compatibility.
  IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='id') THEN
    ALTER TABLE public.profiles ADD COLUMN id TEXT;
    ALTER TABLE public.profiles ADD PRIMARY KEY (id);
  END IF;

  IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='email') THEN
    ALTER TABLE public.profiles ADD COLUMN email TEXT UNIQUE;
  END IF;

  IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='referral_code') THEN
    ALTER TABLE public.profiles ADD COLUMN referral_code TEXT;
  END IF;
  
  -- The points column should have a default value.
  ALTER TABLE public.profiles ALTER COLUMN points SET DEFAULT 1000;

END $$;


-- Step 3: Update the trigger function to use the new ID generator.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- Insert a new profile record. The ID is generated by our custom function.
  -- The welcome bonus of 1000 points is set as the default value on the table.
  INSERT INTO public.profiles (id, user_id, email, referral_code)
  VALUES (
    public.generate_unique_short_id(), 
    new.id, 
    new.email,
    new.raw_user_meta_data->>'referral_code'
  );
  RETURN new;
END;
$$;


-- Step 4: Ensure the trigger is active on the auth.users table.
-- Dropping and recreating is a safe way to ensure the latest version of the function is used.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

